name: C++ Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Compile C++ code
        run: g++ 68174ba2-1b99-4741-a283-94dd19ced75d.cpp -o dipole

      - name: Run program
        run: ./dipole
